### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by njohns-grovo**
Good Morning!
This change is a small documentation update to expose the default gobuild configuration.

### CODE REVIEW

**Comment by cep21** [comment]
Hi,

gobuild works great for us at SignalFx, but I haven't invested much time to make it work for other environments.  If you run into any troubles or need for extra configuration, please let me know or submit a pull request.

**Comment by njohns-grovo** [comment]
Hello,
We're in the initial stages of supporting go for production so we're hitting a lot of pain points with CircleCi so gobuild has been really useful.  I am working on adding gox support to gobuild right now so if that might be useful I can send in a PR.

**Comment by cep21** [comment]
One thing I've discovered when building out gobuild and circleutil is that gobuild is best containing the things developers may want to know about while circleutil is best for things that only the build system cares about.  For example, both need to discover coverage or lint information so that belongs in gobuild.  But gox is something that the build system probably only cares about, so gox stuff may work best as bash functions inside circleutil/scripts/common.sh

**Comment by njohns-grovo** [comment]
I've worked with it a bit more over the weekend (and today) and I agree with that.  I have some other things which may be just not obvious on my part but i'll put those in an issue instead.

Thanks!

**Pull request merged**
